phpcs:
    standard: .phpcs.xml
    # can be overriden by CLI: phpqa --tools phpcs:1
    allowedErrorsCount: 0
    # number of allowed errors is compared with warnings+errors, or just errors from checkstyle.xml
    ignoreWarnings: false
    # https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting
    reports:
        cli:
        - full
        file:
            # checkstyle is always included and overriden
            checkstyle: checkstyle.xml
            # you can include custom reports (https://github.com/wikidi/codesniffer/blob/master/reports/wikidi/Summary.php#L39)
            # ./vendor/owner/package/src/MySummaryReport.php: phpcs-summary.html
phpcbf:
    standard: .phpcs.xml
    # can be overriden by CLI: phpqa --tools phpcs:1
    allowedErrorsCount: 0
    # number of allowed errors is compared with warnings+errors, or just errors from checkstyle.xml
    ignoreWarnings: false

phpmd:
    allowedErrorsCount: 0
    standard: .phpmd.xml

pdepend:
# coverageReport: build/coverage-clover.xml

phpcpd:
    allowedErrorsCount: 0
    minLines: 5
    minTokens: 70

phpmetrics:
    # v1
    config: null
    # v2
    git: false
    # junit: build/log-junit.xml
    # composer: composer.json


tool:
    phpcbf: PlanB\QA\Tools\Analyzer\Phpcbf



